### PR TITLE
Ex 01

### PR DESCRIPTION
**Pull request by nimve**
Here is an attempt at Exercise 1. Hope it looks ok!

### CODE REVIEW

**Comment by huynhngoc** [comment]
PEP8 violation. No python files submitted.
Did you run your code in Syder or Jupyter notebook then copy it to the exercises folder?

Failed (Yngve said this case is an immediate fail)
I'm sorry but you are allowed to fail maximum 2 small exercises and 1 big assignment.

Things to do
1. Rename all files with `.py` as the extension
1. The exercise files should be inside ex01 folder (for this exercise, then similarly, the files for exercise 2 should be in ex02 folder)
1. Rerun code inspection and fix them.

Note, any of the following make you fail:

- PEP8 violation
- Syntax error (code cannot run)
- Late submission
- Repeat the error you made in the last exercises

**Comment by nimve** [comment]
I wrote the code in Pycharm, but created the files in wrong folder originally, and moved them after completion. I must have changed the file types inadvertently in the process, and assumed everything was in order as the code is visible under "Files changed". Could you confirm whether you're able to see the code itself? Are there more mistakes than the file type? What exactly are you referring to as PEP8 violation in this case? Any answers would be greatly appreciated!

**Comment by huynhngoc** [comment]
All of your files don't have `.py` file extension.
Please follow the screenshot to get what I meant.
image
image
image
image
image

**Review by huynhngoc — APPROVED** [review]
Approved as exempt from PEP8 errors in either ex01 or ex02

**Pull request merged**
